### ISSUE TITLE
Emoji showing up as boxes in comments

### ISSUE THREAD

**Issue by tirkarthi** [python/miss-islington#108]
It seems that the robot face emoji and pick emoji are showing up as boxes when @miss-islington adds Thanks and Sorry comments in PRs. I tested it on latest Firefox nightly and Chrome 67 on Mac OS with both of them showing boxes. The same case with README too.

Thanks

**Comment by Mariatta** [comment]
Hi, can you give me the PR number where this is happening so I can take a look? Thanks.

**Comment by tirkarthi** [comment]
Ref comment : https://github.com/python/cpython/pull/7691#issuecomment-397787437

Sorry, I don't know if this is specific to my machine. I can see even the README showing up boxes for the emojis . I have added a screenshot of the same (please ignore the custom black CSS). Feel free to close this if it's not reproducible and I will check back later on my linux machine.

![screen shot 2018-06-16 at 11 35 17 am](https://user-images.githubusercontent.com/3972343/41496281-7b954bf8-7159-11e8-8305-6f642f114d07.png)

**Comment by tirkarthi** [comment]
I think this has something to do with my browser or OS. It works fine on mobile. Closing it. Sorry for the noise.
