### ISSUE TITLE
"Backport status check is done, and it's a success white_check_mark ." hiccup

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#109]
Hum, the bot wrote "@vstinner: Backport status check is done, and it's a success white_check_mark." twice, the second message came 8 minutes after the first one:
https://github.com/python/cpython/pull/7824#issuecomment-398751645

**Comment by Mariatta** [comment]
Yeah this happens when two status checks are finished at the same time. Not sure if there's anything much we can do about it. 🤷‍♀️ 
I'll say we'll just learn to ignore this hiccup :)
