### ISSUE TITLE
Copy skip-issue and skip-news tags to backports

### ISSUE THREAD

**Issue by zooba** [python/miss-islington#11]
When backporting an issue that has skip-issue and skip-news tags, the backport should get those tags too, otherwise the checks will fail.

**Comment by Mariatta** [comment]
I requested @bedevere-bot to do this 😅   https://github.com/python/bedevere/issues/26

**Comment by Mariatta** [comment]
Applying labels to Pull request requires write access to the repository.
@miss-islington does not have such permission, @bedevere-bot does.
So I'm closing this issue, and we'll track it in bedevere :) Thanks!
