### ISSUE TITLE
Don't wait for unrequired status checks.

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#130]
In backport PRs, if all the `required` status checks have completed, then go ahead and merge the PR.
Don't need to wait for the unrequired status checks.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/72 (Add a status check for reverted commits), https://github.com/python/core-workflow/issues/76 (Turn off code coverage status checks), https://github.com/python/core-workflow/issues/19 (Don't wait for allowed_failures on travis builds?), https://github.com/python/miss-islington/issues/109 ("Backport status check is done, and it's a success white_check_mark ." hiccup), and https://github.com/python/core-workflow/issues/269 (Improve guidance to core devs on checking CLA status).

**Comment by Mariatta** [comment]
Required status checks for a branch can be looked up via: https://developer.github.com/v3/repos/branches/#get-required-status-checks-of-protected-branch

**Comment by Mariatta** [comment]
The actual API we want to use is: https://developer.github.com/v3/repos/branches/#list-required-status-checks-contexts-of-protected-branch

But this is currently blocked because miss-islington doesn't have the right permission to access that API endpoint.

**Comment by arhadthedev** [comment]
No longer relevant after https://github.com/python/core-workflow/issues/498.
