### ISSUE TITLE
CLA check for this repo?

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#15]
Perhaps this repo needs @the-knights-who-say-ni but I don't know how to set that up.

**Comment by merwok** [comment]
If we want to avoid special-cases in Bevedere, what’s needed is a bugs.python.org user linked to the github user.  If you create one, I think I have the access to check the «signed CLA» box, if people agree it’s a good idea.

**Comment by terryjreedy** [comment]
I have been thinking that a bpo user would be a good solution.  More than one person should have the password (however the GH account is handled).

**Comment by merwok** [comment]
Let’s get @python/infrastructure-staff into the loop

**Comment by Mariatta** [comment]
This is done.
