### ISSUE TITLE
Remove HTML comments from PR descriptions before automerge

### ISSUE THREAD

**Issue by zware** [python/miss-islington#150]
See https://github.com/python/cpython/commit/50c99d917c0eded2afcad0a3d7e49475a76440a3 for example

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/miss-islington/issues/97 (Stop 'Thanks' comments.), and https://github.com/python/devguide/issues/17 (Remove mentions of Mercurial).
