### ISSUE TITLE
Rate limited since the automerge has been deployed.

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#153]
Automerge feature caused miss-islington to reach rate limit.
Need to figure out what to do about it.

**Comment by vstinner** [comment]
I started a discussion: https://discuss.python.org/t/miss-islington-hits-github-api-rate-limits/5246

**Comment by arhadthedev** [comment]
Closing because miss-islington no longer automerges commits:

- https://github.com/python/core-workflow/issues/498
