### ISSUE TITLE
Keep track of who triggered the automerge

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#155]
Perhaps we can add a line in commit message of who applied the ":robot: automerge" label.
Something like: "approved by: Core Dev"

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/miss-islington/issues/153 (Rate limited since the automerge has been deployed.), https://github.com/python/miss-islington/issues/9 (Trigger the backport when labels were updated), https://github.com/python/devguide/issues/30 (Keeping github branch in sync with master), and https://github.com/python/miss-islington/issues/7 (Trigger the backport by leaving comments to miss-islington).

**Comment by raginisai** [comment]
I am working on making our pull requests merge automatically if a certain set of conditions are true.

However, I have not been successful yet and therefore kindly ask for your help!

I am using the adaptavist ScriptRunner for Bitbucket version 4.5.2 (Self-hosted Bitbucket).

[Python Course Institute in Bangalore](http://www.trainingbangalore.in/python-training-in-bangalore.html)

[Python Online Training](https://www.gangboard.com/app-programming-scripting-training/python-training)
