### ISSUE TITLE
can the preserve the author of the original commit in the squash merge?

### ISSUE THREAD

**Issue by benjaminp** [python/miss-islington#16]
```
$ git show -s b03623227ed1264e3cac4e6bb4878d96b91aa484 --pretty=fuller
commit b03623227ed1264e3cac4e6bb4878d96b91aa484
Author:     Miss Islington (bot) <31488909+miss-islington@users.noreply.github.com>
AuthorDate: Thu Sep 7 11:35:03 2017 -0700
Commit:     Benjamin Peterson <benjamin@python.org>
CommitDate: Thu Sep 7 11:35:03 2017 -0700

    [3.6] fixes bpo-31373: fix undefined floating-point demotions (GH-3396) (#3424)
    
    (cherry picked from commit a853a8ba7850381d49b284295dd6f0dc491dbe44)
```
The author metadata should be from the original commit not stamped over. (e.g., so the Author should still be me in the above example)

I'm not sure if this is actually possible, since GitHub is actually doing the author rewrite during the squash.

**Comment by Mariatta** [comment]
We can't preserve it in squash merge. Rebase merge maybe.

**Comment by zware** [comment]
It is possible to set the committer explicitly for a commit, using `git -c "user.name=Your Name" -c "user.email=Your email"`, and to extract committer information from the cherry-picked commit.  It's not exactly straightforward, but I think GitHub should preserve the committer and author of the commit rather than the pull request.  Maybe.

**Comment by Mariatta** [comment]
When we do squash merge into a single commit, GitHub takes the info of the PR author, not the original committer. 

If we allow rebase merge, I think we can do the `git -c "user.name=Your Name"` thing and the original author's info can be retained this way.

If the rebase merge is allowed, it will have to be enabled for all branches including `master`. And the core dev merging a PR needs to know that for backport PR, use rebase merge option, for `master` PRs, use the squash merge option.

**Comment by berkerpeksag** [comment]
By the way, I proposed allowing rebase merges when we discussed implementing a merge bot with @brettcannon and @Mariatta. They asked me to explain what exactly I'm proposing but I got sidetracked with other issues.

I can write a document and send it to core-workflow if you want to fix this issue.

**Comment by Mariatta** [comment]
GitHub just introduced Commit co-author feature. I'll investigate of how this can fit for miss-islington.
https://github.com/blog/2496-commit-together-with-co-authors

**Comment by Mariatta** [comment]
I tested the co-author feature in:  https://github.com/python/cpython/commit/6ea75b174da0cf824e2acc5db6b53798f5f4e4f9

What do you all think about it? Would this be a good solution? I.e. having two co-authors to the commit?
I can code it such that the `co-authored by` footer is always added in backport PR.

**Comment by Mariatta** [comment]
`Co-authored-by` is now being added by default by miss-islington.
So I think it addressed your concern about preserving the author. The side effect is that they're sharing the credit with miss-islington.

Do you all think it's ok to close this issue now?

**Comment by berkerpeksag** [comment]
IMO, the use of co-author feature is a workaround (better than nothing of course, thanks!) I will report this to GitHub so let's keep the issue open for a while.

**Comment by berkerpeksag** [comment]
Just got a response from GitHub:

> I can definitely understand how the ability to specify an author for a squashed PR merge might be useful. I've just added your +1 to that feature request internally. I can't say if or when a change will happen, but your feedback is in the right hands.

**Comment by Mariatta** [comment]
I consider this as won't fix, and closing the issue.
If GitHub will fix it soon, great, then there is nothing to do on our side.
If GitHub doesn't fix it, well, IMO the bot did make the PR, it can have the credit.
The `co-authored by` line is sufficient to me.
