### ISSUE TITLE
Remove bpo link in automerge commit

### ISSUE THREAD

**Issue by zhangyangyu** [python/miss-islington#162]
Could we remove bpo link in automerge commit? It's somewhat duplicate, also make the backport commit message not neat. It seems currently backport commit message removes the bpo link, any real need to apply two different strategies?

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/miss-islington/issues/38 (Remove [X.Y] from the backport commit message), https://github.com/python/miss-islington/issues/150 (Remove HTML comments from PR descriptions before automerge), https://github.com/python/devguide/issues/164 (Remove/Update the paragraph about Squashing Commits in Committing.rst), https://github.com/python/core-workflow/issues/74 (Add bpo link to mention-bot when issue id provide), and https://github.com/python/core-workflow/issues/223 (GH-5550 was linked to bpo-12345).

**Comment by Mariatta** [comment]
I agree that the bpo link can be removed in the automerge.

**Comment by vstinner** [comment]
automerge creates ugly commit message :-(

```
commit f0e0f2008d160cdd7e5bc02ea61c43f8c7b2b82f
Author: Raymond Hettinger <rhettinger@users.noreply.github.com>
Date:   Sun Nov 25 16:24:52 2018 -0800

    bpo-35300: Add usage note to the lru_cache() docs (GH-10707)
    
    
    
    https://bugs.python.org/issue35300
```

3 empty lines and an useless link (`bpo-35300: ` already provides the same info).

**Comment by berkerpeksag** [comment]
I've opened https://github.com/python/miss-islington/pull/314 to fix this issue.
