### ISSUE TITLE
If the original author and the committer is the same...

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/miss-islington#18]
I just have merged my first PR after miss-islington become working. If the original author and the committer is the same person, miss-islington's comment's look slightly strange.

> Thanks @serhiy-storchaka for the PR, and @serhiy-storchaka for merging it

> Sorry, @serhiy-storchaka and @serhiy-storchaka, I could not cleanly backport this to 3.6 due to a conflict.

This is low priority, but I think that it would be nice to not duplicate the name in this case.

Thank you for your awesome work @Mariatta! Your tools help a lot!

**Comment by Mariatta** [comment]
Thanks @serhiy-storchaka 😄 
I updated the bot, now if the committer and PR author is the same, only one of them gets mentioned.

**Comment by serhiy-storchaka** [comment]
Thank you @Mariatta!
