### ISSUE TITLE
Is there anything we need to do to prevent automerging to security-fix-only branches?

### ISSUE THREAD

**Issue by ned-deily** [python/miss-islington#184]
Now that the cpython 3.6 branch is moving to security-fix-only mode, per our prior practice I have now restricted merges on the 3.6 branch to release managers and administrators.  That made me wonder whether that restriction applies to our GitHub bots, particularly the automerge bot.  Since I can't easily test this from my GitHub account (as I'm in the release manager team!), does anyone know whether automerges have been being blocked for 3.5 and/or could test for 3.6?

**Comment by Mariatta** [comment]
There is nothing to be done :)
miss-islington doesn't currently have the permission to push to restricted branches like 3.4, 3.5.
Perhaps just remove the needs backport to 3.6 label.
Thanks!

**Comment by ned-deily** [comment]
OK, thanks!
