### ISSUE TITLE
Leave a comment when automerge failed

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#188]
Miss-islington should leave a comment if merging failed, e.g. if it doesn't have the right permission to merge into protected branch.
At the moment it fails silently.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/miss-islington/issues/7 (Trigger the backport by leaving comments to miss-islington), https://github.com/python/miss-islington/issues/150 (Remove HTML comments from PR descriptions before automerge), https://github.com/python/miss-islington/issues/97 (Stop 'Thanks' comments.), https://github.com/python/miss-islington/issues/26 (Notify when backport PRs failed), and https://github.com/python/devguide/issues/331 (make check in devguide failing).

**Comment by raginisai** [comment]
Excellent   blog, I wish to share your post with my folks circle. It’s really helped me a   lot, so keep sharing post like this
--
[Python Online training](https://www.gangboard.com/app-programming-scripting-training/python-training)
[Python Course institute in Bangalore](http://www.trainingbangalore.in/python-training-in-bangalore.html)
