### ISSUE TITLE
Broken bot on https://github.com/python/cpython/

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#219]
The bot is still broken: https://github.com/python/cpython/pull/12383#issuecomment-473846779 the bot is working for 14 minutes to create a backport, whereas previously it took less than 5 minutes (usually less than 1 minute).

https://discuss.python.org/t/broken-miss-inlington/1030

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/301 (The cpython github merge webhook to bugs.python.org is broken), https://github.com/python/devguide/issues/79 (https://docs.python.org/devguide/ is broken?), https://github.com/python/core-workflow/issues/239 (Bot for Github labels), https://github.com/python/core-workflow/issues/11 (python/cpython doesn't have tags), and https://github.com/python/devguide/issues/231 (Update links to point to https://devguide.python.org/).

**Comment by vstinner** [comment]
cc @ewdurbin

**Comment by vstinner** [comment]
Oh, there another bug: https://github.com/python/cpython/pull/12383 has been merged into the master branch, but https://bugs.python.org/issue36317 didn't get a new comment. Something is wrong.

**Comment by ewdurbin** [comment]
spot checks:
  1) no failed web hook deliveries to bugs.python.org in last 24 hours.
  2) no failed web hook deliveries to miss-islington in last 24 hours.

**Comment by JulienPalard** [comment]
We reverted cherry_picker to 1.2.2, is it better now?

**Comment by vstinner** [comment]
I confirm that the bot is repaired: https://github.com/python/cpython/pull/12489 3.7 backport created successfully.
