### ISSUE TITLE
Hanging ....

### ISSUE THREAD

**Issue by terryjreedy** [python/miss-islington#23]
When I merged https://github.com/python/cpython/pull/2494 with a backport label, I got this message.

Thanks @wohlganger for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6.

An hour later, .... nothing.

I ran cherry_picker the old way and in 10-15 seconds had
https://github.com/python/cpython/pull/3487.

**Comment by Mariatta** [comment]
Thanks @terryjreedy I've seen this happened, and still figuring out the solution.
Sometimes it will work again when I remove and re-add the label to retrigger the backport.
I know it's not optimal  😞

**Comment by terryjreedy** [comment]
Just curious -- has the process quit or been killed, or is it stuck in a loop or become a zombie?

**Comment by Mariatta** [comment]
It quit (uncaught exception) before it can leave a comment about not being able to backport ... 
Re-applying the label will kick off a new process.

**Comment by Mariatta** [comment]
This happened twice today. I'll read the logs later to find out what's going on.

**Comment by terryjreedy** [comment]
For https://github.com/python/cpython/pull/2573, I did not add the backport label until after merging, but the bot tried to backport anyway.  I did not notice until after I did the backport manually.  Not sure if that was one of the hangs.

After backporting  by hand, I realized I should have asked the bot make an initial backport (by tagging before the merge), even if incorrect, planning to pull the PR to add the changes I already knew were needed for 3.6, test,and then push.  (Just as with any other contribution.)

**Comment by Mariatta** [comment]
The hanging caused because there were two backports going on at the same time, two processes trying to access the same git repository.
In https://github.com/python/miss-islington/pull/32 I made it so that only one backport can happen at any time. If you notice more situations where it's hanging please re-open :)
