### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#243]
> I'm having trouble backporting to 3.7. Reason: 'Error 110 while writing to socket. Connection timed out.'. Please retry by removing and re-adding the needs backport to 3.7 label.

Issue seen at: https://github.com/python/cpython/pull/13816#issuecomment-498758309

**Comment by Mariatta** [comment]
Re-tried and it worked. This is intermittent issue with celery 😥

**Comment by vstinner** [comment]
I didn't see the issue recently, I close it.
