### ISSUE TITLE
Notify when backport PRs failed

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#26]
In https://github.com/python/cpython/pull/3548, the pr backports cleanly without conflict, but the test suite failed.

Some ideas of what @miss-islington can do:

- notify the original PR author, or the core dev merging the PR, that the backport failed (leave a comment)
- automatically close the backport PR? because it now requires manual backport. A core dev can close it too.
- re-add the needs backport to [X.Y] label to the original PR

**Comment by Mariatta** [comment]
Can't re-add the label since it'll trigger another auto-backport .. :thinking:

**Comment by terryjreedy** [comment]
If the PR merges back cleanly, leave it alone.  Miss Islington has done here job.  Let the author and core dev decided whether to close and start over with git cherry-pick or to pull the backport patches.  (I assume that Miss Islington allows edits.)  The latter should usually be easier.

I would like to always get an email when Travis and Appveyor finish a backport test, so there is no or less need to keep checking in the browser.

**Comment by Mariatta** [comment]
> I would like to always get an email when Travis and Appveyor finish a backport test, so there is no or less need to keep checking in the browser.

Sounds good. I can make Miss Islington leave a comment once the status checks are done, and she can mention the PR author and the core dev who merged the PR.
During the sprint some core devs also wanted to have this notification for regular PRs too.

**Comment by Mariatta** [comment]
https://github.com/python/cpython/pull/3618#issuecomment-329985595 is an example where @miss-islington leaves a comment when all status checks are done.
