### ISSUE TITLE
"Automerge-Triggered-By: @githubhandle" message causes spam

### ISSUE THREAD

**Issue by zware** [python/miss-islington#270]
Since miss-islington uses a GitHub handle in the "Automerge-Triggered-By" 'header', whoever triggered the automerge gets spammed any time a contributor does something strange in their own fork of the repo that causes a new commit with the same "Automerge-Triggered-By" message to be pushed to their fork.  For example, I was just notified about [this commit](https://github.com/PatrikKopkan/cpython/commit/855cd8bdf99e156e9baee55dd45f6e39b671ed68) this morning.

I would prefer using display name (`Zachary Ware`, possibly with email address if public) rather than GitHub handle (`@zware`) for this message, which also makes it easier to tie the committer to the commit since the GitHub handle is not actually present anywhere else in the Git repository.

**Comment by Mariatta** [comment]
Will #275 works for you, or having full name instead is still desired?

**Comment by zware** [comment]
I'd still prefer full name to parallel the `Co-Authored-By:` format, but #275 is a nice simple improvement that's ready to go :)

**Comment by merwok** [comment]
Would be great to get #275 merged for now!

**Comment by zware** [comment]
AFAICT, there's no way to fully parallel `Co-Authored-By:`; we'd have to do an API call to get the display name (counting against our AFAIK already stressed rate limit), and even then we wouldn't necessarily get the email address.  I'm afraid we'll have to settle for something like `GH:<username>`, and just count on our external record-keeping to map things correctly when we eventually move away from GitHub in 5-30 years :)

#275 appears to be linked to the wrong issue (I don't think it will actually affect #272) and misses a bit of cleanup, so I've created #405 to hopefully finally get this one fixed :)
