### ISSUE TITLE
Show command in error message

### ISSUE THREAD

**Issue by tiran** [python/miss-islington#29]
Miss Islington would be even more helpful if she would just tell me the right command. For example https://github.com/python/cpython/pull/3674#pullrequestreview-64066873 has comment

> Sorry @felipeochoa and @tiran, I had trouble checking out the 2.7 backport branch.
> Please backport using cherry_picker on command line.

She has all the information to tell me the right hash and branch(es):

> Sorry @felipeochoa and @tiran, I had trouble checking out the 2.7 backport branch.
> Please backport using cherry_picker on command line:
> ```
> cherry_picker 19e4d93 2.7``.
> ```

**Comment by Mariatta** [comment]
Great idea! Thanks. Definitely can be done :)
