### ISSUE TITLE
Remove duplicate Co-authored-by trailer

### ISSUE THREAD

**Issue by berkerpeksag** [python/miss-islington#315]
It seems like GitHub has adapted our workaround to the authorship problem in backport commits as their 'official' solution. As a result of that we are now having two duplicate `Co-authored-by` trailers in backport PR messages.

**Comment by Mariatta** [comment]
Do you have link where I can read up more about what's changed from GitHub side?

**Comment by berkerpeksag** [comment]
I haven't done much research on this yet, but I saw the same behavior on a non-Python repository. I'll try to add some screenshots this week.

**Comment by berkerpeksag** [comment]
Here's a screenshot from my [test repository](https://github.com/fayton/cpython/pull/5):

![image](https://user-images.githubusercontent.com/26338/75243636-ef6f0300-57d2-11ea-8229-935d55542a62.png)

The noreply email is from my $WORK account.

**Comment by Mariatta** [comment]
That seems to be a feature in GitHub web UI only.

I don't see duplicated co-authored-by in recent commits through the API.

**Comment by Mariatta** [comment]
I don't think this is a problem with miss-islington. The duplicated co-authored-by comes from the GitHub UI which you need to manually edit.
