### ISSUE TITLE
Strip markdown from commit message when automerge is used

### ISSUE THREAD

**Issue by berkerpeksag** [python/miss-islington#317]
Here's a recent example: https://github.com/python/cpython/commit/8af4712a16e4b7d1b60f1faec13cd7a88da95f6a

```
# [bpo-39128](https://bugs.python.org/issue39128): happy eyeballs description

# [3.9] 39128 - happy eyeballs description (GH-18624)
# [3.8] 39128 - happy eyeballs description (GH-18624)



https://bugs.python.org/issue39128
```

Rendered version: https://github.com/python/cpython/pull/18624#issue-378714935

![image](https://user-images.githubusercontent.com/26338/75214143-3a6a2580-5795-11ea-98f4-72e9695eba1a.png)

We could easily skip lines that are starting with `#`, but the rest may be so easy to achieve.

**Comment by arhadthedev** [comment]
Closing because miss-islington no longer automerges commits:

- https://github.com/python/core-workflow/issues/498.
