### ISSUE TITLE
"I'm working now to backport" comment added, but then no PR is created

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#342]
The PR https://github.com/python/cpython/pull/20412 had "needs backport to 3.9" label when merged, miss-islington commented "Thanks @tiran for the PR tacotada.. I'm working now to backport this PR to: 3.9." but 10 minutes, no PR was created.
* Second try: I removed/added the label again, nothing
* Christian removed/added the label the 2nd time: nothing

:-(

How can we investigate such issue? Who can help on such issue?

@Mariatta or @ewdurbin: do you have access to the Heroku logs?

**Comment by Mariatta** [comment]
There was bug in latest celery https://github.com/celery/celery/issues/6153
I've reverted to previous version for now.

**Comment by terryjreedy** [comment]
And on retry the failed backport worked.
