### ISSUE TITLE
Remove 'Automerge-Triggered-By' from PR body when removing the automerge label

### ISSUE THREAD

**Issue by lysnikolaou** [python/miss-islington#357]
Would it make sense to remove the `Automerge-Triggered-By` text from the PR body, when removing the `automerge` label?

I could prepare a PR for this, if you agree that this is a nice-to-have.

**Comment by Mariatta** [comment]
You mean if a core dev applied the automerge label, but removed it/changed their mind before the automerge happened?

Ok then yeah I think it would be good to remove the `Automerge-Triggered-By` line from the PR in that situation.

Thanks.

**Comment by lysnikolaou** [comment]
> You mean if a core dev applied the automerge label, but removed it/changed their mind before the automerge happened?

What would you say would be the correct thing to do if another core-dev removed the `automerge` label? (Or even another triager)

**Comment by Mariatta** [comment]
If another coredev rremoved the automerge label, then I think it is ok to remove the "Automerge-Triggered-By" line.

However if a triager removed it, that's a separate concern.
We have logic where if a triager adds the "automerge" label, the bot will automatically remove the label. This label is meant for core devs only. If a triager removed the label, I would expect the label to be added back in.

**Comment by lysnikolaou** [comment]
> If another coredev rremoved the automerge label, then I think it is ok to remove the "Automerge-Triggered-By" line.

Agreed! 

> However if a triager removed it, that's a separate concern.
> We have logic where if a triager adds the "automerge" label, the bot will automatically remove the label. This label is meant for core devs only. If a triager removed the label, I would expect the label to be added back in.

The thing is a triager can close a PR after the automerge label has been applied, thus disabling it, right? If that's so, then I think a triager should also be able to remove the label itself.

**Comment by Mariatta** [comment]
I think if the triager close the PR with automerge label in it, the automerge label should be left as is.

Sometimes we close and re-open PR just to restart the CI. automerge label should not be automatically removed just because the PR is closed.

**Comment by lysnikolaou** [comment]
> I think if the triager close the PR with automerge label in it, the automerge label should be left as is.
> 
> Sometimes we close and re-open PR just to restart the CI. automerge label should not be automatically removed just because the PR is closed.

Right! Ok, I'll have a go at it, probably tomorrow.

**Comment by Mariatta** [comment]
Ok thanks!!
