### ISSUE TITLE
Prepare for the 3.10 beta release

### ISSUE THREAD

**Issue by pablogsal** [python/miss-islington#446]
Once we publish the first beta release for Python 3.10 we need to make sure that miss-islington supports:

* The 3.10 backport label.
* The rename of master to main.

It would be ideal if we can synchronize so this is ready for the release :)

CC: @brettcannon @Mariatta

**Comment by Mariatta** [comment]
There shouldn't be any issue with supporting the 3.10 label. We can update the test case to be sure, perhaps by parametrizing it.

https://github.com/python/miss-islington/blob/ac121b7808929853a99ca22c26eb31f9dde56e8c/tests/test_backport_pr.py#L123

 
Re branch rename, the easiest is by creating the `cherry-picker.toml` file that says that specifies the `default_branch` config value. I will look into preparing the PR for it, and wait for it to be merged until after the 3.10 release.

There is also an open ticket for supporting the `main` branch by default. https://github.com/python/cherry-picker/issues/21

**Comment by Mariatta** [comment]
Added test that we can backport to the 3.10 branch correctly: https://github.com/python/miss-islington/pull/453 This should be safe to be merged now.

Added the config for the `main` branch. https://github.com/python/miss-islington/pull/452 This should wait until we have the `main` branch.
