### ISSUE TITLE
Approved backport PR not merged whereas all CI tests passed

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#458]
Hi,

I approved the backport of my PR, but even after all CI tests passed, the backport PR was not merged: https://github.com/python/cpython/pull/26290

I merged the PR manually.

The PR has 1 pending reviewer (markshannon), is it related? Is it required that all pending reviewers review backport PRs?

**Comment by Mariatta** [comment]
One of the tests have the status of "Skipped", instead of "Success".
Since it was not run, miss-islington could not merge it.
![Screen Shot 2021-05-21 at 3 53 35 PM](https://user-images.githubusercontent.com/5844587/119205468-24f1b300-ba4d-11eb-942a-cbdae67cd4ac.png)

**Comment by vstinner** [comment]
> One of the tests have the status of "Skipped", instead of "Success".

Would it be possible to modify the bot to merge the PR if jobs are skipped?

**Comment by arhadthedev** [comment]
The issue manifests itself again. Here are examples of PRs that have no failing checks but were not merged by miss-islington:

- https://github.com/python/cpython/pull/103680
- https://github.com/python/cpython/pull/13951
- https://github.com/python/cpython/pull/103682

**Comment by arhadthedev** [comment]
I digged a little and now see that this is intended because of gh-610 is merged. Probably, <kbd>🤖  automerge</kbd> should be removed to not confuse core developers.
