### ISSUE TITLE
Backport PR no created

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#462]
Hi,

The PR https://github.com/python/cpython/pull/26489 had "needs backport to 3.10" label when I merged it. No backport PR was created.

I removed the label and then added it again. Still no backport.

@miss-islington, I miss you :-(

**Comment by Mariatta** [comment]
Getting 503 errors. I will investigate.

**Comment by Mariatta** [comment]
Thanks for raising the issue. It looks like miss-islington is working again, and I could see that the backport PR has been created for you.
