### ISSUE TITLE
Strip backport PR number from the commit message

### ISSUE THREAD

**Issue by berkerpeksag** [python/miss-islington#53]
From https://devguide.python.org/gitbootcamp/#backporting-merged-changes

> Example of good backport commit message:
>
> bpo-12345: Improve the spam module (GH-777)
>
> * Add method A to the spam module
> * Update the documentation of the spam module
>
> (cherry picked from commit 62adc55)

I agree that the backport PR's number is rarely useful and it would be nice to remove it automatically. Can miss-islington strip the backport PR number in the commit message?

**Comment by Mariatta** [comment]
Yes, done in https://github.com/python/miss-islington/issues/53.

**Comment by berkerpeksag** [comment]
Awesome, thank you very much @Mariatta :)
