### ISSUE TITLE
Islington reports status check being a success but also reports ❌ when checks fail

### ISSUE THREAD

**Issue by DanielNoord** [python/miss-islington#564]
I noticed this in https://github.com/python/cpython/pull/94734 and this comment: https://github.com/python/cpython/pull/94734#issuecomment-1180046528

The checks clearly fail:
https://github.com/python/cpython/pull/94734/checks

Islington reports the checks as both being a success but uses the emoji that's being used to indicate that the checks failed.

Relevant code seems to be:
https://github.com/python/miss-islington/blob/6e5de75d26129312cce195eb2d15acd93e11dbd7/miss_islington/status_change.py#L102-L112

This seems rather straightforward so I'm not immediately sure what is broken here. Can there be some sort of race condition where `result["state"]` is `"success"` on L103 but has changed when we reach L112?

**Comment by DanielNoord** [comment]
Oh no, I'm stupid. This is actually pretty straightforward. If `result["state"] == "success"` but there are timed out checks then the f-string will still use "success" even though the `if success` check fails.
That should be easily fixable. Working on a PR.

**Comment by jacobtylerwalls** [comment]
Interesting. I fixed this in #501 but it was re-caused by a faulty merge in #481. Goes to show the value of tests.
