### ISSUE TITLE
CLA status not transferred to backport PRs

### ISSUE THREAD

**Issue by vsajip** [python/miss-islington#597]
I'm not sure if this is a miss-islington or a cla-bot issue, but here goes. On [GH-101164 ](https://github.com/python/cpython/pull/101164) the author is marked as having signed the CLA, but when backports were created (via setting the "needs backport to ..." labels), the [3.10](https://github.com/python/cpython/pull/101183) and [3.11](https://github.com/python/cpython/pull/101184) backport PRs indicate that the CLA _isn't_ signed and thus block merging.

**Comment by hugovk** [comment]
I think what happened is the contributor uses different email addresses for committing and for their GitHub profile, and when we squash commits we lose the original commits' email and instead use the profile email in the squash commit.

---

They used one email address for the commits (`@yandex-team.ru`) in [GH-101164](https://github.com/python/cpython/pull/101164).

You can quickly check that by appending `.patch` to https://github.com/python/cpython/pull/101164 -> https://github.com/python/cpython/pull/101164.patch

Looking at the edit history of the CLA bot comment on the original PR https://github.com/python/cpython/pull/101164#issuecomment-1397559267, the hadn't signed the CLA to begin with, and then signed it with their `@yandex-team.ru`, making the bot happy.

The the PR was squashed and merged. This loses the info from the original commits, and I suspect instead puts an email from their GitHub profile: `@galqiwi.ru`. (You can see this for https://github.com/python/cpython/commit/8cdbc4609022c9c8dfb66da328a149c2bea75f89 locally or at https://github.com/python/cpython/commit/8cdbc4609022c9c8dfb66da328a149c2bea75f89.patch.)

So when the backport PRs were made, we no longer have the original commits' address and are using the GH one in the squashed commit.

Check the edit history for CLA bot in a PR:

https://github.com/python/cpython/pull/101184#issuecomment-1398087184

It said `@galqiwi.ru` hadn't signed the CLA.

(It looks like the author then signed again with their second address, making the bot happy.)

**Comment by hugovk** [comment]
Also cc @ambv.

**Comment by vsajip** [comment]
Good catch, @hugovk. I've asked the committer to sign the CLA using their non-Yandex email address.
