### ISSUE TITLE
Trigger the backport by leaving comments to miss-islington

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#7]
Would be nice to be able to trigger the backport after PR has been merged, in case that people forgot to apply the `needs backport` label.

Some thoughts:
- Allow people to leave a comment like "@miss-islington backport this" or something like that
- Perhaps this ability should be restricted to the PR author or core devs or even core dev who merged the PR. So if a random person or another bot leaves the comment, miss-islington will ignore it.

**Comment by zware** [comment]
Could it check for the `needs backport` label being applied post-merge?

**Comment by Mariatta** [comment]
We can do that too.

**Comment by Mariatta** [comment]
Triggering backport by adding the needs backport label has been done in #10, and it seems to work quite well.
I think it's not needed to trigger the backport by leaving comments. So I'm closing this issue.
