### ISSUE TITLE
Odd backport failure

### ISSUE THREAD

**Issue by terryjreedy** [python/miss-islington#70]
When I merged https://github.com/python/cpython/pull/5981 with backport labels, the usual backport PRs were generated and I approved both.  https://github.com/python/cpython/pull/5986 for 3.7 went normally.  https://github.com/python/cpython/pull/5987 for 3.6 got hung-up waiting for Appveyor to report.  I could not check details because there was no details link.  Miss I. twice said "Backport status check is done, and it's a success", which usually triggers a merge.   To try to restart CI, I closed and opened, but Miss I. reclosed, permanently.

I went back to original PR and re-added 3.6 backport label.  https://github.com/python/cpython/pull/5993 then proceeded normally.

I don't know that there is anything to do, except to take notice of a new? failure mode.

**Comment by Mariatta** [comment]
Thanks! I did see a couple 500 errors from PR python/cpython#5987. I will investigate later this evening.

With miss-islington's PRs, once the PR is closed (whether merged or not merged), the branch will automatically be deleted. Once the branch is deleted, we can't reopen the PR. All we can do is to retrigger the backport by re-applying the labels. Sorry for the inconvenience.
