### ISSUE TITLE
Issue numbers being dropped

### ISSUE THREAD

**Issue by brettcannon** [python/miss-islington#73]
E.g. https://github.com/python/cpython/pull/6048 start out with no `bpo` in the title. Had this happen as second time earlier today on another set of backports related to https://bugs.python.org/issue32758 .

**Comment by Mariatta** [comment]
While the PR on master has bpo number, the squashed commit didn't have the bpo number.
 https://github.com/python/cpython/commit/10485ebd40669d3e17ab4f477c8c898543bcccd1

**Comment by brettcannon** [comment]
So I take it GitHub doesn't look at the modified title but what the initial title was? That's annoying.

**Comment by Mariatta** [comment]
Yeah so we need to always make sure the bpo- number is in the commit message, and edit it as necessary before merging.
