### ISSUE TITLE
Assign the failed PR to be backported to the core dev who merged it

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#88]
If miss-islington failed to backport a PR, she can assign the PR to the core developer who merged it.

**Comment by terryjreedy** [comment]
That seems reasonable, but what would the effect be?  Can I search for unmerged PRs assigned to me?  (In ignorance of any benefit, most people ignore the Assignees field and just merge when ready.)  Or, can I search for unmerged issues that touch idlelib?  If the devguide has anything about searching cpython prs, I could not find it.  A search page for the tracker would be even nicer, though that could use an update to add an 'unmerged' PR field.

**Comment by Mariatta** [comment]
You can periodically go to GitHub and look at pull requests assigned to you.

**Comment by Mariatta** [comment]
Closed via #90
